site_name: Chương trình phổ thông
site_description: Nơi tổng hợp nội dung học và hướng dẫn cho chương trình phổ thông.
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

# Make changes to the nav section
nav:
  - Home: 'index.md'
  - 'Hướng dẫn':
    - 'Giáo trình': 'guide.md'
    - 'Plan': 'notice.md'
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false