site_name: Sử dụng máy tính một cách năng suất và bảo mật
site_description: Nâng cao năng suất làm việc đồng thời bảo vệ bản thân tốt hơn trên không gian mạng khi sử dụng máy tính.
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - Home: 'index.md'
  - 'Hướng dẫn':
    - 'Khởi đầu': 'gioi-thieu.md' 
    - 'Internet?': 'guide.md'
    - 'Công cụ - tối ưu': 'cong-cu-toi-uu.md'
  - 'Năng suất':
    - 'Phương pháp Zettelkasten': 'zettelkasten.md'
    - 'Quản lý kiến thức - Obsidian': 'obsidian.md'
    - 'Ôn tập hiệu quả - Anki': 'anki.md'
    - 'Plain Text: Văn bản thuần': 'plain-text.md'
  - 'Bảo mật & Riêng tư':
    - 'Linux': 'linux-in-a-nutshell.md'    
    - 'An toàn trên mạng': 'an-toan-tren-mang.md'
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false