site_name: Sử dụng Linux và các công cụ tối ưu cho công việc.
site_description: Nâng cao năng suất làm việc đồng thời bảo vệ bản thân tốt hơn trên không gian mạng khi sử dụng máy tính.
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - Home: 'index.md'
  - 'Linux':
    - 'Mở đầu': 'gioi-thieu.md'
    - 'Chuyển nhà': 'installation-guide.md' 
    - 'Terminal': 'guide.md'
    - 'Lựa chọn Tools': 'cong-cu-toi-uu.md'
  - 'Công cụ':
    - 'Obsidian': 'obsidian.md'
    - 'Anki': 'anki.md'
    - 'Orgmode': 'org-mode.md'
  - 'Bảo mật & Riêng tư':
    - 'Bảo mật trong Linux': 'linux-security.md'    
    - 'An toàn trên mạng': 'net-safety.md'
  - 'Tài nguyên':
    - 'Tài nguyên': 'tai-nguyen.md'
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false