site_name: Immersion-based Vietnamese Learning 
site_description: How to actually acquire Vietnamese
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections

nav:
  - Home: 'index.md'
  - 'Guide':
    - 'Vietnamese Guide': 'guide.md'
  - 'Yomitan':
    - 'Yomitan for Vietnamese Dictionary': 'yomi-setup.md'
  - 'Hán Nôm':
    - 'Guide': 'han-nom.md'
  - 'Resources':
    - 'Resources': 'resources.md'
  - 'Vietnamese Media Recommendation':
    - 'Novels': 'books.md'
    - 'Movies': 'movies.md'
    - 'Youtube': 'youtube.md'
    - 'Comprehensible Input': 'input.md'
      
theme:
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: cyan 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material
