site_name: Học cách học
site_description: Tự học cách học tập, làm việc tối ưu và hiệu quả.
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - Home: 'index.md'
  - 'Hướng dẫn':
    - 'Giáo trình': 'guide.md'
  - 'Công cụ học tập':
    - 'Ghi nhớ cùng Anki': 'anki.md'
    - 'PKM với Obsidian': 'obsidian.md'
    - 'Quản lý lịch trình': 'calendar.md'
    - 'OKR cho cá nhân': 'okr.md'
  - 'Phương pháp ghi chú':
    - 'PARA': 'para.md'
    - 'Chỉ mục': 'indexing-method.md'
    - 'Hộp gỗ': 'zettelkasten.md'
  - 'Phương pháp học tập':
    - 'Siêu học tập': 'ultralearn.md'
    - 'Lặp lại ngắt quãng': 'srs.md'


      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false