site_name: Học Tiếng Ấn Độ (Hindi) thông qua Comprehensible Input
site_description: Một trang tự học Tiếng Ấn Độ (Hindi) thông qua những tài nguyên miễn phí và có sẵn trên mạng.
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - Home: 'index.md'
  - 'Hướng dẫn':
    - 'Chung': 'guide.md'
    - 'Nói': 'noi.md'
    - 'Đọc': 'doc.md'
    - 'Ngữ pháp': 'ngu-phap.md'
  - 'Đầu vào dễ hiểu':
    - 'Hướng dẫn': 'input.md'
    - 'Tài nguyên': 'input-res.md'
  - 'Công cụ':
    - 'Anki': 'anki.md'
  - 'Tài nguyên':
    - 'Tài nguyên': 'resources.md'
  - 'Nội dung tiêu thụ':
    - 'Youtube': 'youtube.md'
    - 'Podcasts': 'podcasts.md'
      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false