site_name: Giáo trình khoa học máy tính OSSU
site_description: Giáo trình khoa học máy tính/Công nghệ thông tin dựa trên giáo trình của OSSU, nay có bản Tiếng Việt.
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - Home: 'index.md'
  - 'Hướng dẫn':
    - 'Giáo trình': 'guide.md'
  - 'Lộ trình':
    - 'Java Backend': 'java-backend.md'
    - 'Phát triển Web': 'webdev-roadmap.md'
    - 'Lập trình Rust': 'rust.md'
  - 'Tài nguyên':
    - 'Tài nguyên': 'resources.md'
    - 'Danh sách Video bài giảng': 'day-du.md'  
      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false