site_name: Tiếng Anh Chuyên Ngành (ESP)
site_description: Hướng dẫn tự học Tiếng Anh chuyên ngành thông qua các nguồn miễn phí.
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - Home: 'index.md'
  - 'Hướng dẫn': 
    - 'Hướng dẫn': 'guide.md'
    - 'Đọc': 'reading.md'
    - 'Nghe': 'listening.md'
    - 'Từ vựng': 'vocab.md'
  - 'Chuyên ngành':
    - 'Y học': 'y-hoc.md'
    - 'Marketing': 'marketing.md'
    - 'CNTT - IT': 'cntt.md'
    - 'Du lịch': 'du-lich.md'
    - 'May mặc': 'may-mac.md'
    - 'Điện tử': 'dien-tu.md'
  - 'Tài nguyên':
    - 'Tài nguyên': 'resources.md'
      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false