site_name: Sống khỏe
site_description: Những gợi ý để cải thiện sức khỏe thể chất và tinh thần trong cuộc sống.
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - Home: 'index.md'
  - 'Hướng dẫn':
    - 'Tìm hiểu chung': 'guide.md'
    - 'Chăm sóc bản thân': 'self-care.md'
  - 'Sức khỏe':
    - 'Thể chất': 'physical_health.md'
    - 'Tinh thần': 'mental-health.md'
  - 'Tài liệu':
    - 'Tham khảo': 'sources.md'
      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false