site_name: Học Tiếng Anh qua Phim Ảnh và Youtube
site_description: Tự học Tiếng Anh thông qua việc tiêu thụ nội dung Tiếng Anh (Immersion).
site_author: onlyduyy  
theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo

nav:
  - Home: 'index.md'
  - 'Guide':
    - 'Hướng dẫn chính': 'guide.md'
    - 'Đầu vào dễ hiểu ': 'dau-vao.md'
    - 'Tổng hợp ngữ pháp': 'ngu-phap.md'
  - 'Khu tài nguyên':
    - 'Tài nguyên học': 'resources.md'
  - 'English Media Recommendation':
    - 'Văn Học': 'sach.md'
    - 'Phim Ảnh': 'phim-anh.md'
    - 'Youtube': 'youtube.md'
      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material

extra:
  generator: false